# .github/workflows/run-node-scripts.yml
name: Run Node.js Scripts

on:
  push:
    branches:
      - main

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16' # Specify the Node.js version required

    - name: Install dependencies
      run: npm install

    - name: Run ls.js
      run: node ls.js

    - name: Run frs.js
      run: node frs.js

    - name: Run afs.js
      run: node afs.js
